# Site settings
title: Higor Moreno Ribeiro
email: higormorenoribeiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Precisa colocar descrição mesmo? Pode ser depois?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://higormorenoribeiro.github.io" # the base hostname & protocol for your site
github_username:  higormoreno

# Build settings
markdown: kramdown
